{{- if and .Values.persistence.enabled .Values.persistence.thumbnails.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adhive.thumbnailsPVC" . }}
  labels:
    {{- include "adhive.labels" . | nindent 4 }}
    component: thumbnails
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.thumbnails.size | quote }}
{{- end }}
